### ISSUE TITLE
RouterをVyOSからUbuntuに乗り換え

### ISSUE THREAD

**Issue by logica0419** [ictsc/ictsc-drove#2]
さくらのクラウドの方でVyOSが公式アーカイブとしてサポートされなくなってしまって久しいため  
VyOSのアーカイブを自前で作り続けるよりは、VyOSの代わりとなるOSSをUbuntuに乗っけたい

BGP Peerとして動けばいいので、BIRDとか載せると行けそう  
https://qiita.com/mtkboooo/items/14d2cd59e7145a73116d

**Comment by logica0419** [comment]
ついでに、Elastiflow使って外部からのフローを検知したいと思ってるので、hsflowdみたいなflow exporterとElastiflowぶっこんで動かすところまでやってくれるとさらにありがたいなぁ…と思っています

**Comment by Crow314** [comment]
この間別件でBIRDをUbuntuに載せてみたんですが、netplan (or systemd-networkd)と相性問題が発生したっぽいので少し悩みどころ (このときはOSを almalinux に変えて解決した)

**Comment by Crow314** [comment]
↓ このあたり見る限り ifupdown を使えば良さそう？

https://github.com/IPA-CyberLab/IPA-DN-CommonAnsible/blob/1df8a0c8899609163f889628ab954055f3e3b0dc/roles/prepare_linux/tasks/prepare_Debian.yml#L52-L89

**Comment by Crow314** [comment]
systemd-networkd の問題っぽそう？
https://homenoc-community.slack.com/archives/C02V0RJ3H7Y/p1683207169719829

**Comment by logica0419** [comment]
almalinuxならさくらに公式イメージあるので、almaでもいい説はある
Ubuntuで統一できるならわかりやすくていいけど、でもそのために設定をごちゃごちゃいじるのであればalmaにしたほうがむしろわかりやすいかなと思ったりします

**Comment by Crow314** [comment]
素直に↓見るのであればDebianのが良さげかも
https://github.com/IPA-CyberLab/IPA-DN-EasyBgpStarterKit

正直RHEL系を使っているところは宗教の色が強いので、どこまで宗教色を残していいものかというのは

**Comment by logica0419** [comment]
debianでいいと思います
僕はまじでルーター無知なので判断は任せる

**Comment by Crow314** [comment]
debianでガチャガチャやってみて、だめだったらalmaに逃げるくらいでやってみます

**Comment by Crow314** [comment]
Ubuntuで行ける気がしたので取り敢えずUbuntuで
